apiVersion: v1
kind: Service
metadata:
<<<<<<< HEAD
<<<<<<< refs/remotes/pingidentity/master
  name: pingdataconsole
  labels:
    app: pingdataconsole
=======
  name: pingdataconsole-service
>>>>>>> remove labels from yaml and put into kustomization commonLabels
=======
  name: pingdataconsole-service
>>>>>>> master
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: pingdataconsole
---
apiVersion: apps/v1
kind: Deployment
metadata:
<<<<<<< HEAD
<<<<<<< refs/remotes/pingidentity/master
  name: pingdataconsole
  labels:
    app: pingdataconsole
=======
  name: pingdataconsole-deployment
>>>>>>> remove labels from yaml and put into kustomization commonLabels
=======
  name: pingdataconsole-deployment
>>>>>>> master
spec:
  replicas: 1
  template:
    metadata:
      name: pingdataconsole
    spec:
      containers:
      - name: pingdataconsole
        image: pingidentity/pingdataconsole:edge
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "1.5Gi"
            cpu: "1"
          limits:
            memory: "1.5Gi"
            cpu: "1"
